coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - crates
        paths: 
          - "crates/*"
        branches: 
          - main
        if_ci_failed: error
        informational: true
        only_pulls: false
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
ignore:
  - "tools/*"
