name: Turbo Trigger
inputs:
  workspace:
    description: Name for npm package name
    required: true
  run_on_push:
    description: Flag to always trigger the workflow on push events
    required: false
    default: false
outputs:
  trigger:
    description: "Boolean value to trigger or not trigger the workflow"
    value: ${{ steps.turbo.outputs.trigger }}
runs:
  using: "composite"
  steps:
    - name: Fetch Head
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Turbo Pull Request
      id: turbo
      shell: bash
      run: |
        git checkout -- pnpm-lock.yaml
        if [ ${{ github.event_name }} == 'merge_group' ]; then
          npx turbo-ignore ${{ inputs.workspace }} --fallback ${{ github.event.merge_group.base_sha }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
        elif [ ${{ github.event_name }} == 'pull_request' ]; then
          npx turbo-ignore ${{ inputs.workspace }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
        elif [ ${{ github.event_name }} == 'push' ]; then
          if [ "${{ inputs.run_on_push }}" == "true" ]; then
            echo "trigger=true" >> "$GITHUB_OUTPUT"
          else
            npx turbo-ignore ${{ inputs.workspace }} --fallback ${{ github.event.before }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "trigger=true" >> "$GITHUB_OUTPUT"
        fi
