name: Turbo Trigger
inputs:
  workspace:
    description: Name for npm package name
    required: true
outputs:
  trigger:
    description: "Boolean value to trigger or not trigger the workflow"
    value: ${{ steps.turbo.outputs.trigger }}
runs:
  using: "composite"
  steps:
    - name: Fetch Head
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Turbo Pull Request
      id: turbo
      shell: bash
      run: |
        git checkout -- pnpm-workspace.yaml
        if [ ${{ github.event_name }} == 'merge_group' ]; then
          npx turbo-ignore ${{ inputs.workspace }} --fallback ${{ github.merge_group.base_sha }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
        elif [ ${{ github.event_name }} == 'pull_request' ]; then
          npx turbo-ignore ${{ inputs.workspace }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
        else
          echo "trigger=true" >> "$GITHUB_OUTPUT"
        fi
