name: Brew Install
runs:
  using: "composite"
  steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Homebrew dependencies
        shell: bash
        run: |
          brew bundle --file=./Brewfile
