name: Rust Install
runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain
      uses: mkroening/rust-toolchain-toml@main
    - name: Install Rust Utilities
      uses: taiki-e/install-action@v1
      with:
        tool: nextest,cargo-llvm-cov,clippy-sarif,sarif-fmt,cargo-deny
    - name: Run cache
      uses: Swatinem/rust-cache@v2
    - name: Rust Cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ matrix.os }}-cargo-
    - if: runner.name == 'self-hosted'
      name: Rust Buildjet Cache
      uses: buildjet/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ matrix.os }}-cargo-
    - name: Set cargo environments
      shell: bash
      run: |
        echo "CACHE_TIMEOUT_MINUTES=5" >> $GITHUB_ENV
        echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
        echo "CARGO_NET_RETRY=10" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
    - if: runner.os == 'Linux'
      name: Install missing dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwebkit2gtk-4.0-dev build-essential curl wget libglib2.0-dev libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev libappindicator-dev libgdk3.0-cil libatk1.0-dev libpq-dev binutils
