name: Rust Install
# Borrowd from https://github.com/paradigmxyz/reth/pull/1355/files
inputs:
  sccache_region:
    description: Region of sccache s3 bucket
    default: auto
    required: false
  sccache_bucket:
    description: Sccache s3 bucket name
    default: sccache
    required: false
  sccache_endpoint:
    description: Sccache s3 endpoint
    required: true
  sccache_key_id:
    description: Sccache s3 key id
    required: true
  sccache_secret:
    description: Sccache s3 key secret
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Rust and Cargo
      shell: bash
      run: |
        if ! command -v cargo &> /dev/null; then
          curl https://sh.rustup.rs -sSf | sh -s -- -y
        fi
    - name: Install Rust Toolchain (nightly)
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Install Rust Utilities
      uses: taiki-e/install-action@v1
      with:
        tool: nextest,cargo-llvm-cov
    - name: Install Mold
      uses: rui314/setup-mold@v1
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Rust Cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ matrix.os }}-${{ matrix.target }}-cargo-
    - name: Set sccache environments
      shell: bash
      run: |
        echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
        echo "SCCACHE_S3_USE_SSL=true" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    - name: Start sccache
      shell: bash
      run: |
        ${SCCACHE_PATH} --start-server
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.sccache_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.sccache_secret }}
        SCCACHE_BUCKET: ${{ inputs.sccache_bucket }}
        SCCACHE_ENDPOINT: ${{ inputs.sccache_endpoint }}
        SCCACHE_REGION: ${{ inputs.sccache_region }}
