[package]
name = "wallet-rs-cli"
description = "A CLI for wallet-rs"
version = "0.1.1"
edition = "2021"

authors = ["Shun Kakinoki"]
license = "MPL-2.0"
repository = "https://github.com/wallet-rs/wallet-rs"
readme = "README.md"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo"] }
ethers-signers = { workspace = true }
eth-keystore = "0.5.0"
eyre = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "env-filter",
    "ansi",
    "tracing-log",
] }
wallet-metamask = { workspace = true }
