name: PR Validate
inputs:
  github_token:
    description: Github token
    required: true
runs:
  using: "composite"
  steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
