name: Java Install
runs:
  using: "composite"
  steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 12
      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r24
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Ktlint
        shell: bash
        run: |
          curl -s https://api.github.com/repos/pinterest/ktlint/releases/latest \
            | grep "browser_download_url.*ktlint" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
          chmod a+x ktlint && mv ktlint /usr/local/bin/
