name: Rust Install
runs:
  using: "composite"
  steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 12
      - name: Install NDK
        shell: bash
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;24.0.8215888" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libclang-dev libopencv-dev
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Add cargo to path
        shell: bash
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "RUST_ANDROID_GRADLE_CARGO_COMMAND=$HOME/.cargo/bin" >> $GITHUB_ENV
