name: Android
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
jobs:
  android-lint:
    env:
      RUSTFLAGS: -D warnings
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Install Rust Toolchain (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Install NDK
        shell: bash
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;24.0.8215888" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Gradle Lint
        run: |
          ./gradlew lint
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
        continue-on-error: false
  # android-test:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Fetch Head
  #       uses: actions/checkout@v3
  #     - name: Rust Install
  #       uses: ./.github/actions/rust-install
  #       with:
  #         sccache_endpoint: ${{ secrets.SCCACHE_ENDPOINT }}
  #         sccache_key_id: ${{ secrets.SCCACHE_KEY_ID }}
  #         sccache_secret: ${{ secrets.SCCACHE_SECRET }}
  #     - name: Java Install
  #       uses: ./.github/actions/java-install
  #     - name: Gradle Test
  #       run: |
  #         ./gradlew test
