name: Android
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Rust Install
        uses: ./.github/actions/rust-install
        with:
          sccache_endpoint: ${{ secrets.SCCACHE_ENDPOINT }}
          sccache_key_id: ${{ secrets.SCCACHE_KEY_ID }}
          sccache_secret: ${{ secrets.SCCACHE_SECRET }}
      - name: Java Install
        uses: ./.github/actions/java-install
      - name: Gradle Lint
        run: |
          ./gradlew lint
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
        continue-on-error: false
  android-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Rust Install
        uses: ./.github/actions/rust-install
        with:
          sccache_endpoint: ${{ secrets.SCCACHE_ENDPOINT }}
          sccache_key_id: ${{ secrets.SCCACHE_KEY_ID }}
          sccache_secret: ${{ secrets.SCCACHE_SECRET }}
      - name: Java Install
        uses: ./.github/actions/java-install
      - name: Gradle Test
        run: |
          ./gradlew test
