name: iOS
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
jobs:
  ios-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  ios-test:
    runs-on: macos-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Install Rust Toolchain (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Make iOS
        run: |
          make ios
      - name: Run Unit Tests
        working-directory: ./ios
        run: |
          set -o pipefail && xcodebuild test-without-building -project WalletCore.xcodeproj -scheme WalletCoreTests -destination 'platform=iOS Simulator,name=Any iOS Simulator Device,OS=latest' -resultBundlePath TestResults.xcresult | xcpretty --color --simple
      # - name: Build App
      #   working-directory: ./ios
      #   run: |
      #     xcodebuild -project WalletCore.xcodeproj -scheme WalletCore -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - if: always()
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: ios/TestResults.xcresult
