name: iOS
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  ios-turbo:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      trigger: ${{ steps.turbo.outputs.trigger }}
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Turbo Trigger
        id: turbo
        uses: ./.github/actions/turbo-trigger
        with:
          workspace: "ios"
  ios-lint:
    needs:
      - ios-turbo
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: needs.ios-turbo.outputs.trigger == 'true'
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew Install
        uses: ./.github/actions/brew-install
      - name: Install Homebrew dependencies
        run: |
          brew update
          brew bundle --file=./Brewfile
      - name: Run swiftlint
        run: |
          swiftlint
      - name: Run swift-format
        run: |
          swift-format lint --recursive .
  ios-test:
    needs:
      - ios-turbo
    runs-on: macos-latest
    timeout-minutes: 90
    if: needs.ios-turbo.outputs.trigger == 'true'
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Rust Install
        uses: ./.github/actions/rust-install
      - name: Install Ruby Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"
      - name: Make iOS
        run: |
          make ios
      - name: Run Unit Tests
        working-directory: ./ios
        run: |
          bundle exec fastlane test
  ios-check:
    if: always()
    needs:
      - ios-turbo
      - ios-lint
      - ios-test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: ios-lint,ios-test
          jobs: ${{ toJSON(needs) }}
