name: Node
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
jobs:
  node-build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - name: Install Rust Toolchain
        uses: mkroening/rust-toolchain-toml@main
      - name: Node Install
        uses: ./.github/actions/node-install
      - name: Node Build
        run: |
          pnpm run build
  node-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: mkroening/rust-toolchain-toml@main
      - name: Node Install
        uses: ./.github/actions/node-install
      - name: Node Lint
        run: |
          pnpm run lint
  node-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: mkroening/rust-toolchain-toml@main
      - name: Node Install
        uses: ./.github/actions/node-install
      - name: Node Test
        run: |
          pnpm run test
  node-check:
    if: always()
    needs:
      - node-build
      - node-lint
      - node-test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
