name: PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: read
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: PR Validate
        uses: ./.github/actions/pr-validate
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  pr-check:
    if: always()
    needs:
      - pr-lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
