name: PR
on:
  pull_request_target:
jobs:
  pr-lint:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: PR Validate
        uses: ./.github/actions/pr-validate
  pr-check:
    if: always()
    needs:
      - pr-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
