name: PR
on:
  pull_request_target:
jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: PR Validate
        uses: ./.github/actions/pr-validate
