name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Get Release Info
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          command: manifest
          monorepo-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
  cargo:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Rust Install
        uses: ./.github/actions/rust-install
      - name: Rust Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Publish Crates
        uses: katyo/publish-crates@v2
        with:
          ignore-unpublished-changes: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
