name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          command: manifest
          monorepo-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
  cargo:
    needs: release-please
    # if: ${{ needs.release-please.outputs.release_created == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: katyo/publish-crates@v2
        with:
          path: './crates'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
