name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get Release Info
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          command: manifest
          monorepo-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
  cargo:
    env:
      RUSTFLAGS: -D warnings
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    needs: release-please
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Rust Install
        uses: ./.github/actions/rust-install
        with:
          sccache_endpoint: ${{ secrets.SCCACHE_ENDPOINT }}
          sccache_key_id: ${{ secrets.SCCACHE_KEY_ID }}
          sccache_secret: ${{ secrets.SCCACHE_SECRET }}
      - name: Rust Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Publish Crates
        uses: katyo/publish-crates@v2
        with:
          ignore-unpublished-changes: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
