name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          command: manifest
          monorepo-tags: true
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
      - if: ${{ steps.release.outputs.releases_created }}
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
