name: Rust
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always
jobs:
  rust:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true
          # - os: ubuntu-latest
          #   target: x86_64-linux-android 
          - os: macos-latest
            target: x86_64-apple-ios
            test: false
          - os: macos-latest
            target: x86_64-apple-darwin
            test: true
          # - os: windows-latest
          #   target: x86_64-pc-windows-msvc
    env:
      RUSTFLAGS: -D warnings
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Install Rust Toolchain (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: "v0.4.0"
      - name: Rust Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.target }}-cargo-
      - name: Rust Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
      - name: License Check
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --package mpl-license-checker
      - name: Rust Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
      - if: matrix.test
        name: Rust Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }}
      - if: matrix.test
        name: Rust Coverage Install
        uses: taiki-e/install-action@cargo-llvm-cov
      - if: matrix.test
        name: Rust Coverage
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - if: matrix.test
        name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false
      - name: Rust Clippy Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Print sccache stats
        run: |
          ${SCCACHE_PATH} --show-stats
      - name: Save Rust Cache
        uses: actions/cache/save@v3
        if: failure()
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
